### ISSUE TITLE
'content' property with empty string is assign a non-empty string

### ISSUE THREAD

**Issue by macrini** [kdzwinel/SnappySnippet#54] opened 2017-07-20 19:09 UTC
The 'content' property in pseudo-elements ':before' and ':after' gets an improper assignment of empty strings like this:

#DIV_1:after {
content: '""';
}

The proper value should be just the empty string ''. In other words, 'content' is being assigned an empty string ("") inside another string (the outer ''). So the outer string isn't empty when it should be, and that is a problem.

You can try it at https://www.nytimes.com on any article box featured in the main page. It happens in other websites too.

**Comment by kdzwinel** [comment] 2017-09-08 12:48
Thanks for reporting - that's a duplicate of #38

**Closed by kdzwinel** 2017-09-08 12:48 UTC
